currencies:
  - EUR
  - USD
  - GBP
  - JPY
  - AUD
  - CAD
  - CHF
  - CNY
  - SEK
  - NZD
  - MXN
  - SGD
  - HKD
  - NOK
  - KRW
  - TRY
  - RUB
  - INR
  - BRL
  - ZAR
  - DKK
  - PLN
  - TWD
  - THB
  - IDR
  - HUF
  - CZK